---
- name: create Multiple Users
  hosts: all
  become: yes
  tasks:
  - name: Add several users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
      groups: "wheel"
    loop:
       - testuser1
       - testuser2
# EOF