- name: Deploy Node.js App
  hosts: servers
  become: yes
  tasks:

    - name: Install required dependencies
      apt:
        name:
          - nodejs
          - npm
          - git
        state: present
        update_cache: yes

    - name: Clone the Node.js repository
      git:
        repo: "https://github.com/ItsArsalanMD/nodejs.git"
        dest: "/home/{{ ansible_user }}/nodejs_app"
        version: main
        force: yes

    - name: Install Node.js dependencies
      npm:
        path: "/home/{{ ansible_user }}/nodejs_app"
        state: present

    - name: Start the Node.js application
      command: "node src/index.js"
      args:
        chdir: "/home/{{ ansible_user }}/nodejs_app"
      async: 1000
      poll: 0
      register: app_status

    - name: Display application status
      debug:
        msg: "Node.js app is running in the background"
