---
- name: Privilege Escalation in Ansible
  hosts: target
  become: true
  tasks:
    - name: Update Package List
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache (Debian)
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache (RHEL-based)
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Enable and Start Apache Service
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: started
        enabled: true