---
- name: AWS S3 Bucket Upload - Ansible
  hosts: localhost
  tasks:
  - name: Upload/PUT file to S3 bucket
    amazon.aws.aws_s3:
      profile: personal
      bucket: nubeerabucket
      mode: put
      object: "2021/12/Screenshot.png"
      src: "/home/ubuntu/Screenshot.png"
    register: putresult

  - debug: msg="{{ putresult.msg }} and the S3 Object URL is {{putresult.url}}"
    when: putresult.changed