- name: Setup Docker and run Node.js project
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - git
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone the Node.js project from GitHub
      git:
        repo: "https://github.com/ItsArsalanMD/nodejs.git"
        dest: "/opt/nodejs_project"
        version: master

    - name: Build Docker image for Node.js project
      docker_image:
        name: "nodejs_image"
        source: build  # Corrected source parameter
        build:
          path: "/opt/nodejs_project"  # Directory containing Dockerfile
        state: present

    - name: Run Docker container from built image
      docker_container:
        name: nodejs_container
        image: "nodejs_image"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"